spring:
  application:
    name: spring-cloud-provider #配置工程名，注意如果是集群的话工程名都保持一致
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_db01
    username: root
    password: zzw1234
    
server:
  port: 8090
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.asiainfo.entity
  mapper-locations:
  - classpath:mapper/*.xml
  
eureka:
  client: #eureka客户端配置
    register-with-eureka: true  #是否注册到eureka服务端，由于本工程是客户端所以是要注册的
    fetch-registry: true  #是否获取服务注册信息，由于本工程是客户端是需要调用其它客户端服务的，所以是要获取服务注册信息的
    service-url:  #eureka客户端和服务端的通信地址
#      defaultZone: http://localhost:9000/eureka #配置服务端的地址，此为服务端单机版配置
      defaultZone: http://eureka-server-1:9000/eureka,http://eureka-server-2:9001/eureka #配置服务端的地址，此为服务端集群配置。注意：eureka-server-1是eureka服务的eureka.instance.hostname的值，不是spring.application.name的值
      
#定义一个可暴露的endpoint端点，从而可以在页面上通过ip:port/actuator/hystrix.stream访问
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream