spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 9001
  
eureka:
  instance:
    hostname: eureka-server-2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server-1:9000/eureka
  server:
    enable-self-preservation: false
    
---
spring:
  profiles: dev
server:
  port: 9001
  
eureka:
  instance:
    hostname: eureka-server-2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server-1:9000/eureka
  server:
    enable-self-preservation: false